net_metrics:
  - rto: "Gauge"
    rtt: "Gauge"
    delivery_rate: "Gauge"
    bytes_send: "Counter"
    bytes_received: "Counter"
    min_rtt: "Gauge"

clu_metrics:
  - assignment_stale: "Counter"
    assignment_timeout_received: "Counter"
    bind_errors: "Counter"
    circuit_breakers.default.cx_open: "Gauge"
    circuit_breakers.default.cx_pool_open: "Gauge"
    circuit_breakers.default.rq_open: "Gauge"
    circuit_breakers.default.rq_pending_open: "Gauge"
    circuit_breakers.default.rq_retry_open: "Gauge"
    circuit_breakers.high.cx_open: "Gauge"
    circuit_breakers.high.cx_pool_open: "Gauge"
    circuit_breakers.high.rq_open: "Gauge"
    circuit_breakers.high.rq_pending_open: "Gauge"
    circuit_breakers.high.rq_retry_open: "Gauge"
    default.total_match_count: "Counter"
    health_check.attempt: "Counter"
    health_check.degraded: "Counter"
    health_check.failure: "Counter"
    health_check.healthy: "Gauge"
    health_check.network_failure: "Counter"
    health_check.passive_failure: "Counter"
    health_check.success: "Counter"
    health_check.verify_cluster: "Counter"
    http1.dropped_headers_with_underscores: "Counter"
    http1.metadata_not_supported_error: "Counter"
    http1.requests_rejected_with_underscores_in_headers: "Counter"
    http1.response_flood: "Counter"
    lb_healthy_panic: "Counter"
    lb_local_cluster_not_ok: "Counter"
    lb_recalculate_zone_structures: "Counter"
    lb_subsets_active: "Counter"
    lb_subsets_created: "Counter"
    lb_subsets_fallback: "Counter"
    lb_subsets_fallback_panic: "Counter"
    lb_subsets_removed: "Counter"
    lb_subsets_selected: "Counter"
    lb_zone_cluster_too_small: "Counter"
    lb_zone_no_capacity_left: "Counter"
    lb_zone_number_differs: "Counter"
    lb_zone_routing_all_directly: "Counter"
    lb_zone_routing_cross_zone: "Counter"
    lb_zone_routing_sampled: "Counter"
    max_host_weight: "Counter"
    membership_change: "Counter"
    membership_degraded: "Gauge"
    membership_excluded: "Gauge"
    membership_healthy: "Gauge"
    membership_total: "Gauge"
    original_dst_host_invalid: "Counter"
    retry_or_shadow_abandoned: "Counter"
    update_attempt: "Counter"
    update_empty: "Counter"
    update_failure: "Counter"
    update_no_rebuild: "Counter"
    update_success: "Counter"
    upstream_cx_active: "Gauge"
    upstream_cx_close_notify: "Counter"
    upstream_cx_connect_attempts_exceeded: "Counter"
    upstream_cx_connect_fail: "Counter"
    upstream_cx_connect_timeout: "Counter"
    upstream_cx_connect_with_0_rtt: "Counter"
    upstream_cx_destroy: "Counter"
    upstream_cx_destroy_local: "Counter"
    upstream_cx_destroy_local_with_active_rq: "Counter"
    upstream_cx_destroy_remote: "Counter"
    upstream_cx_destroy_remote_with_active_rq: "Counter"
    upstream_cx_destroy_with_active_rq: "Counter"
    upstream_cx_http1_total: "Counter"
    upstream_cx_http2_total: "Counter"
    upstream_cx_http3_total: "Counter"
    upstream_cx_idle_timeout: "Counter"
    upstream_cx_max_duration_reached: "Counter"
    upstream_cx_max_requests: "Counter"
    upstream_cx_none_healthy: "Counter"
    upstream_cx_overflow: "Counter"
    upstream_cx_pool_overflow: "Counter"
    upstream_cx_protocol_error: "Counter"
    upstream_cx_rx_bytes_buffered: "Gauge"
    upstream_cx_rx_bytes_total: "Counter"
    upstream_cx_total: "Counter"
    upstream_cx_tx_bytes_buffered: "Gauge"
    upstream_cx_tx_bytes_total: "Counter"
    upstream_flow_control_backed_up_total: "Counter"
    upstream_flow_control_drained_total: "Counter"
    upstream_flow_control_paused_reading_total: "Counter"
    upstream_flow_control_resumed_reading_total: "Counter"
    upstream_http3_broken: "Counter"
    upstream_internal_redirect_failed_total: "Counter"
    upstream_internal_redirect_succeeded_total: "Counter"
    upstream_rq_0rtt: "Counter"
    upstream_rq_active: "Gauge"
    upstream_rq_cancelled: "Counter"
    upstream_rq_completed: "Counter"
    upstream_rq_maintenance_mode: "Counter"
    upstream_rq_max_duration_reached: "Counter"
    upstream_rq_pending_active: "Gauge"
    upstream_rq_pending_failure_eject: "Counter"
    upstream_rq_pending_overflow: "Counter"
    upstream_rq_pending_total: "Counter"
    upstream_rq_per_try_idle_timeout: "Counter"
    upstream_rq_per_try_timeout: "Counter"
    upstream_rq_retry: "Counter"
    upstream_rq_retry_backoff_exponential: "Counter"
    upstream_rq_retry_backoff_ratelimited: "Counter"
    upstream_rq_retry_limit_exceeded: "Counter"
    upstream_rq_retry_overflow: "Counter"
    upstream_rq_retry_success: "Counter"
    upstream_rq_rx_reset: "Counter"
    upstream_rq_timeout: "Counter"
    upstream_rq_total: "Counter"
    upstream_rq_tx_reset: "Counter"
    version: "Gauge"

