net_metrics:
  - rto
  - rtt
  - delivery_rate
  - bytes_send
  - bytes_received
  - min_rtt

agg_metrics:
  - avg
  - avg
  - avg
  - avg
  - avg
  - avg

clu_metrics:
  - assignment_stale
  - assignment_timeout_received
  - bind_errors
  - circuit_breakers.default.cx_open
  - circuit_breakers.default.cx_pool_open
  - circuit_breakers.default.rq_open
  - circuit_breakers.default.rq_pending_open
  - circuit_breakers.default.rq_retry_open
  - circuit_breakers.high.cx_open
  - circuit_breakers.high.cx_pool_open
  - circuit_breakers.high.rq_open
  - circuit_breakers.high.rq_pending_open
  - circuit_breakers.high.rq_retry_open
  - default.total_match_count
  - health_check.attempt
  - health_check.degraded
  - health_check.failure
  - health_check.healthy
  - health_check.network_failure
  - health_check.passive_failure
  - health_check.success
  - health_check.verify_cluster
  - http1.dropped_headers_with_underscores
  - http1.metadata_not_supported_error
  - http1.requests_rejected_with_underscores_in_headers
  - http1.response_flood
  - lb_healthy_panic
  - lb_local_cluster_not_ok
  - lb_recalculate_zone_structures
  - lb_subsets_active
  - lb_subsets_created
  - lb_subsets_fallback
  - lb_subsets_fallback_panic
  - lb_subsets_removed
  - lb_subsets_selected
  - lb_zone_cluster_too_small
  - lb_zone_no_capacity_left
  - lb_zone_number_differs
  - lb_zone_routing_all_directly
  - lb_zone_routing_cross_zone
  - lb_zone_routing_sampled
  - max_host_weight
  - membership_change
  - membership_degraded
  - membership_excluded
  - membership_healthy
  - membership_total
  - original_dst_host_invalid
  - retry_or_shadow_abandoned
  - update_attempt
  - update_empty
  - update_failure
  - update_no_rebuild
  - update_success
  - upstream_cx_active
  - upstream_cx_close_notify
  - upstream_cx_connect_attempts_exceeded
  - upstream_cx_connect_fail
  - upstream_cx_connect_timeout
  - upstream_cx_connect_with_0_rtt
  - upstream_cx_destroy
  - upstream_cx_destroy_local
  - upstream_cx_destroy_local_with_active_rq
  - upstream_cx_destroy_remote
  - upstream_cx_destroy_remote_with_active_rq
  - upstream_cx_destroy_with_active_rq
  - upstream_cx_http1_total
  - upstream_cx_http2_total
  - upstream_cx_http3_total
  - upstream_cx_idle_timeout
  - upstream_cx_max_duration_reached
  - upstream_cx_max_requests
  - upstream_cx_none_healthy
  - upstream_cx_overflow
  - upstream_cx_pool_overflow
  - upstream_cx_protocol_error
  - upstream_cx_rx_bytes_buffered
  - upstream_cx_rx_bytes_total
  - upstream_cx_total
  - upstream_cx_tx_bytes_buffered
  - upstream_cx_tx_bytes_total
  - upstream_flow_control_backed_up_total
  - upstream_flow_control_drained_total
  - upstream_flow_control_paused_reading_total
  - upstream_flow_control_resumed_reading_total
  - upstream_http3_broken
  - upstream_internal_redirect_failed_total
  - upstream_internal_redirect_succeeded_total
  - upstream_rq_0rtt
  - upstream_rq_active
  - upstream_rq_cancelled
  - upstream_rq_completed
  - upstream_rq_maintenance_mode
  - upstream_rq_max_duration_reached
  - upstream_rq_pending_active
  - upstream_rq_pending_failure_eject
  - upstream_rq_pending_overflow
  - upstream_rq_pending_total
  - upstream_rq_per_try_idle_timeout
  - upstream_rq_per_try_timeout
  - upstream_rq_retry
  - upstream_rq_retry_backoff_exponential
  - upstream_rq_retry_backoff_ratelimited
  - upstream_rq_retry_limit_exceeded
  - upstream_rq_retry_overflow
  - upstream_rq_retry_success
  - upstream_rq_rx_reset
  - upstream_rq_timeout
  - upstream_rq_total
  - upstream_rq_tx_reset
  - version

mon_periods: 5
