mode: Lite
domainID: alice
domainKeyData: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBcU92NVA0VjNsbUd6UTBvdFBpanpLWUV2VHRIVTlkNURjaWN6c1ZZV0NaK1c3QVhhCmFqZGVQckpoYXF1UHM3NHNITHRLUzE1Z0ozNGdicXhWR3hYeFVtOGRiRlluZGRnSlBramlNNnh2OFF6NFBXRjcKOXhwZVIvYzhhZU1PNGpaNW9QWkgrYi95QzNQV1BYaEptQ1RHSmo5bGs0L3oxdkRzbjRRdk9wUmdIMmw1dnZzWQo0ZkF5THJTVXNrUzZWODlBbHlqeGR2NW40T2FMZ2pZVHlrLzRBQjJqQ2tqeFgxSTRJOWVIOHhnVGM3bmx1TDR0CndKR3RkcDl6cE95dGk3SmdsbUNLQkZVZ2NGVDF3SEdwYW83QjNvMHdBeWJUcDVYNElXV1RBdnlEU01oSGZNNDMKRmlLdCtDbjV3WEZFQ21QdjJUSjF6V1hIOVFTN0hobFF0akNsVXdJREFRQUJBb0lCQVFDVVJLdStLYlJSOXVlVwpCS0c1a2MvOWVqckFBRVhnbVhxeDA5NzNwUXdxM2oxbVphelUxa3lPMDV2V09VZ2xDS05IaE0wdFltVWJ4UVZLCm4xRUVPVHBjbE5OS3FFUnlsM0Zsaml1ZUY1a2FCN3hNaENoL09GSFE4UjNDQTE2cENBK3lUUG5ZS2JhV2Z0SnAKbWc5ZXo4aHRBZkJ5bVVQNlFmWXYvYUpHMUwyYVUxa3ZhSFFzU3MwbmhNKy9RcFVGMzlqcExiZ1IyOE5xYkxBcApzdzc4cVMvMlhJUUZEYzhlVzlqUi9lTVBaMlhIckcxR2U3cjVtb2xvWDJOTjU4V2krbGZFRDJGZXUwc0xFMkJHCk03ajNuMzhxUVFqSlgwQi9qeGpUak1mTFdhMmtzMzhMY3BsRVZzOVduSHA4ZEhaa2NUMisxZ1VNdFgrUkxnNVoKandNdW5BZUJBb0dCQU5WaXRyYzNIcFVoVGQ5blA1bUFzVFVDcjlid3BSZmNJZll5SVUyaEdHaHFMRUd4VklZawpXazAvNUY3cUhicytUc3hob1dSYVZSMi9Zb2htQWVLbW1ZU2JxNkZSSUlRYjNJUGMxZkNETmcyMUdHNFg5bGJvCmVBNnZ0SHlocUs5VHYwR2xpUjU2WkxWOHRSVzFOOXIybitNQk5hS1hqalh6aVR2WFl6ZlVJV05EQW9HQkFNcW8KRHIrSHJ3VHBrNGozc3lKbm44bElreGFBNjVSMGFyOGVDNVhuTEc2c1ZiS1Y0VjdwUDFjQjAzeTJqQTk2RVdsMworQmVCWUhRQkNkazVvbUVKVGhLbmREWjdibUs3ZWNQYlhjY1BBWEtGV0dlRFgwdmFEVTAxV3luanlVL1g2RVVGCnRNS2lDeHJlTTNkZDYwQVBIdzd0RlVqVU5XWktzUmxQOGJGS1RxeXhBb0dBUTB6MUQrZ2tqeWlINVJRdGJQNjMKNVY1SmsyTW16dFd4S0hNN0tiN0xjZk02cmlWOTRTa0tDaDlDcWVUeEo2TkpPeEQzMUN6aGQ1WnJQMVhjOWwxUgpRZy9QRy92NFkzSmVKSUM4UVRWQkVTV3k1TlpON2E4NFhubHdWWGF2TzAwUW4yWFVUM2FPMk9iU1BseC9sMkg5Cm41MDhDMkg5aW1xYk4vS0E2cFRQU3YwQ2dZRUFubk1oL055d21pMnFmZmYxcHB2UTBnY2RnZ1hRcStVT0pWbnYKZ3dnWnRIcW9FcGFmZko3d09DNGtWaWxBZjBWWTRkYThNbHlrdG02dGJadGplMjFVRHIvQTNHeExsWVN4b3RJYwprMndISEt4bnY1OTIzZzZpUWRESzg0aTNPT2MrSXVGZ1FLR0QvMERtaXBqek84WFc2Y3V5elp1bUdOR2pnSUFDCklEVlNLREVDZ1lFQXRlWGpLTkFjWldJekRDRTV3dWRBcGQ5cWJmTXVjajcxOGExNStPWERZVmNndE1oK2VuODEKTUc5ZFFMVzA0K3ZRelNOMFpMdFlsYVd5OHU3bGtiM0ovUm1ZY2lhaVJxSjgyZDFBT05KUVcvVGsvMCsrNENRNwp6M3BCK05kVHp2STNic0l0U3hPZElHbTUyZ0d1bHRMSVVTdHVTQnFKb0FnWm9USm9UbTJIbW5nPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
logLevel: INFO
liteDeployToken: pqa6ZT4Ny7iVKnMZLEQ69VKfHsInraLy
masterEndpoint: https://root-kuscia-master:1080
runtime: runc
runk:
  namespace: ""
  dnsServers: []
  kubeconfigFile: ""
capacity:
  cpu: ""
  memory: ""
  pods: ""
  storage: ""
image:
  pullPolicy: ""
  defaultRegistry: ""
  registries: []

